// src/lib/errors.ts

export enum ErrorCode {
  // Auth
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_EXISTS = 'AUTH_EMAIL_EXISTS',
  AUTH_ADMIN_REQUIRED = 'AUTH_ADMIN_REQUIRED',
  AUTH_HOST_REQUIRED = 'AUTH_HOST_REQUIRED',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Room
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  ROOM_FULL = 'ROOM_FULL',
  ROOM_LOCKED = 'ROOM_LOCKED',
  ROOM_INVALID_CODE = 'ROOM_INVALID_CODE',
  ROOM_ALREADY_JOINED = 'ROOM_ALREADY_JOINED',
  ROOM_MIN_TEAMS = 'ROOM_MIN_TEAMS',
  ROOM_NO_PLAYER_SET = 'ROOM_NO_PLAYER_SET',
  ROOM_NO_PLAYERS = 'ROOM_NO_PLAYERS',
  NOT_IN_ROOM = 'NOT_IN_ROOM',

  // Bid
  BID_INSUFFICIENT_PURSE = 'BID_INSUFFICIENT_PURSE',
  BID_TOO_LOW = 'BID_TOO_LOW',
  BID_SQUAD_FULL = 'BID_SQUAD_FULL',
  BID_OVERSEAS_LIMIT = 'BID_OVERSEAS_LIMIT',
  BID_MANDATORY_RESERVE = 'BID_MANDATORY_RESERVE',
  BID_LOT_NOT_BIDDING = 'BID_LOT_NOT_BIDDING',
  BID_LOT_EXPIRED = 'BID_LOT_EXPIRED',
  BID_NOT_YOUR_TEAM = 'BID_NOT_YOUR_TEAM',
  BID_ALREADY_HIGHEST = 'BID_ALREADY_HIGHEST',
  BID_RATE_LIMITED = 'BID_RATE_LIMITED',
  BID_INVALID_AMOUNT = 'BID_INVALID_AMOUNT',
  BOT_CANNOT_BID_MANUALLY = 'BOT_CANNOT_BID_MANUALLY',

  // Auction
  AUCTION_NOT_ACTIVE = 'AUCTION_NOT_ACTIVE',
  AUCTION_ALREADY_STARTED = 'AUCTION_ALREADY_STARTED',

  // Player
  PLAYER_SET_LOCKED = 'PLAYER_SET_LOCKED',
  PLAYER_NOT_FOUND = 'PLAYER_NOT_FOUND',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
}

export class AppError extends Error {
  constructor(
    public code: ErrorCode,
    message?: string
  ) {
    super(message ?? code);
    this.name = 'AppError';
  }
}
